### ISSUE TITLE
Global Allocator Error

### ISSUE THREAD

**Issue by blockchainlover2019** [pyth-network/pyth-client-rs#20]
Hi, I am suffering from this error!
```error: the `#[global_allocator]` in this crate conflicts with global allocator in: pyth_client```
In cargo.toml
```
[dependencies]
pyth-client = "0.3.0"
anchor-lang = "0.20.1"
anchor-spl = "0.20.1"
stable-swap-anchor = {version = "1.6.8"}
```

**Comment by ali-bahjati** [comment]
If you are wishing to use pyth-client for your on-chain program you should use no-entrypoint feature to prevent Solana to pick up pyth-client on-chain program.

To use this feature define it in dependencies like this:
`pyth-client = {version = "0.3.0", features = ["no-entrypoint"]}`

**Comment by blockchainlover2019** [comment]
@ali-bahjati, thank you.
I was confused. It was a basis of knowledge in RUST.
